### ISSUE TITLE
[feat] Calculate transaction weight

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/raito#107]
Extend `Encode` trait with `weight` method that computes the size of a particular structure in weight units.

Read more: https://learnmeabitcoin.com/technical/transaction/size/

**Comment by mubarak23** [comment]
s

**Comment by m-kus** [comment]
Waiting for #90 to be completed

**Comment by martinvibes** [comment]
hello @m-kus please let me work on this by the time #90 is completed 
would love to contribute in your repo

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
I have a strong background in Rust programming and systems design, with a focus on serialization and data structures

### How I plan on tackling this issue
I am  blockchain developer with years of experience

 Encode Trait: 
Ensure you comprehend how Encode handles serialization.

Define Weight Calculation: 
Determine the weight units relevant to your context (e.g., byte size).

Implement Method:
Add a weight method to the Encode trait.
In this method, use serialization to compute the size of the structure

**Comment by manlikeHB** [comment]
Hi @m-kus , can i work on this?

**Comment by devcollinss** [comment]
Can I please work on this, @m-kus? I’d love the opportunity to contribute.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
With over 15 years of experience in Web2 development, I am passionate about contributing to open-source projects and am currently expanding my skill set with Rust, Solidity, and, more specifically, Cairo, as part of my involvement with Dojo Coding.

### How I plan on tackling this issue
1. Add a new method called `weight` to the existing `Encode` trait.

2. Implement the `weight` method: 
- Identify and differentiate between the witness and non-witness parts of the transaction.
- Calculate the length of non-witness data.
- Calculate the length of witness data.
- Multiply the length of the non-witness data by 4 to get the weight of non-witness data in weight units.
- Add the weight of the non-witness data to the length of the witness data (since each byte of witness data counts as 1 weight unit) to obtain the total weight of the transaction.

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also an active member of Dojo Coding, where I'm expanding my skills in Cairo and Web3 technologies. I'm eager to learn, contribute, and be part of this project.

### How I plan on tackling this issue
My approach to solving the issue is:
1. Understanding the Encode Trait
2. Designing the weight Method
3. Testing and Validation
4. Documentation

**Comment by aman312118** [comment]
can i work on this

**Comment by m-kus** [comment]
@Jeanmichel7 can you pls do this as a follow up to #120 ?

**Comment by Jeanmichel7** [comment]
@m-kus With pleasure!
