### ISSUE TITLE
Implement `validate_proof_of_work` Function

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/raito#5]
Implement `validate_proof_of_work` function.

Acceptance Criteria:
- implement body of the [function](https://github.com/keep-starknet-strange/raito/blob/c972cf70dd24ffc842ba5b12ca3406011107c107/src/validation.cairo#L32) based on [ZeroSync](https://github.com/ZeroSync/ZeroSync/blob/f1bd4736b0bac190ac48cbc8d5fcd92e2e1be7b9/src/block/block_header.cairo#L255) version
- write unit tests

**Comment by Xavek** [comment]
I want to try this. @b-j-roberts @AbdelStark

**Comment by maciejka** [comment]
@Xavek issue description has been updated. Are you still up to the task?

**Comment by manoahLinks** [comment]
i will love to work on this

**Comment by maciejka** [comment]
Let's give @Xavek few more hours to respond.

**Comment by ricardomazuera** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/raito---bitcoin-zk-client).

### My background and how it can be leveraged
I have +4 years experience as Software Engineer and I write code in Python and Go, currently I'm studying Cairo and I see this is a good first issue because is replicate a function from other repo.

### How I plan on tackling this issue
I'll run the repo locally, understand the function to replicate and replicate it in the code. Then, I'll do the tests.

**Comment by Xavek** [comment]
@maciejka Yes still up for it.

**Comment by maciejka** [comment]
@Xavek how is it going? Any progress?

**Comment by Xavek** [comment]
@maciejka Yes I have drafted a PR regarding this can you have a look I have mentioned in the PR description why it's a draft PR.
